# Generated by Django 5.2.9 on 2025-12-09 13:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('charges_communes_annuelles', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Charges communes annuelles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('numero', models.CharField(max_length=10)),
                ('etage', models.PositiveIntegerField()),
                ('loue', models.BooleanField(default=False)),
                ('loyer_base', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(100.0)], verbose_name='Loyer de base')),
                ('charges_mensuelles', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Charges mensuelles')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.proprietaires')),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartements', to='immeuble.immeuble')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
