# Generated by Django 5.2.6 on 2025-09-11 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immeuble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('nb_etages', models.PositiveIntegerField()),
                ('annee_construction', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=10)),
                ('etage', models.PositiveIntegerField()),
                ('surface', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nb_pieces', models.PositiveIntegerField()),
                ('loue', models.BooleanField(default=False)),
                ('immeuble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immeuble.immeuble')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
