# Generated by Django 5.2.6 on 2025-09-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immeuble', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartement',
            name='nb_pieces',
        ),
        migrations.RemoveField(
            model_name='appartement',
            name='surface',
        ),
        migrations.RemoveField(
            model_name='immeuble',
            name='annee_construction',
        ),
        migrations.RemoveField(
            model_name='immeuble',
            name='nb_etages',
        ),
    ]
