# Generated by Django 5.2.6 on 2025-10-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immeuble', '0002_remove_appartement_nb_pieces_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appartement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='immeuble',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='immeuble',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='immeuble',
            name='charges_communes_annuelles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Charges communes annuelles'),
        ),
    ]
