# Generated by Django 5.2.6 on 2025-10-14 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immeuble', '0003_remove_appartement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 14, 10, 5, 42, 392100)),
        ),
        migrations.AddField(
            model_name='appartement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 14, 10, 5, 42, 392100)),
        ),
        migrations.AddField(
            model_name='immeuble',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
