# Generated by Django 5.2.6 on 2025-10-20 12:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immeuble', '0005_alter_appartement_created_at_and_more'),
        ('persons', '0003_alter_locataires_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persons.proprietaires'),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 12, 12, 52, 746833)),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 20, 12, 12, 52, 746833)),
        ),
    ]
