# Generated by Django 5.2.6 on 2025-10-22 12:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immeuble', '0008_alter_appartement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartement',
            name='charges_mensuelles',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Charges mensuelles'),
        ),
        migrations.AddField(
            model_name='appartement',
            name='loyer_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(100.0)], verbose_name='Loyer de base'),
        ),
        migrations.AlterField(
            model_name='appartement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 12, 15, 31, 751415)),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 12, 15, 31, 751415)),
        ),
    ]
