# Generated by Django 5.2.6 on 2025-10-22 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immeuble', '0009_appartement_charges_mensuelles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 12, 17, 45, 67829)),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 12, 17, 45, 67829)),
        ),
    ]
