# Generated by Django 5.2.6 on 2025-10-22 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immeuble', '0014_alter_appartement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 12, 19, 8, 832187)),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 12, 19, 8, 832187)),
        ),
    ]
