# Generated by Django 5.2.7 on 2025-10-30 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immeuble', '0020_alter_appartement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 10, 8, 14, 680157)),
        ),
        migrations.AlterField(
            model_name='immeuble',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 10, 8, 14, 680157)),
        ),
    ]
