# Generated by Django 5.2.7 on 2025-10-30 10:08

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0005_alter_contrats_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementLocataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 10, 30, 10, 8, 14, 680157))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mois', models.DateField(help_text='Premier jour du mois concerné (ex: 01/01/2025)', verbose_name='Mois concerné')),
                ('loyer', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Loyer payé')),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Charges payées')),
                ('autres', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Autres montants (réparations, etc.)')),
                ('date_paiement', models.DateField(help_text='Date effective de réception du paiement', verbose_name='Date du paiement')),
                ('date_echeance', models.DateField(blank=True, help_text='Date limite de paiement (généralement le 5 du mois)', null=True, verbose_name="Date d'échéance")),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('prelevement', 'Prélèvement automatique')], default='virement', max_length=50, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, help_text='Numéro de chèque, référence virement, etc.', max_length=100, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('recu', 'Reçu'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('partiel', 'Paiement partiel')], default='recu', max_length=20, verbose_name='Statut')),
                ('valide', models.BooleanField(default=True, verbose_name='Paiement validé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_loyers', to='contrats.contrats')),
            ],
            options={
                'verbose_name': 'Paiement locataire',
                'verbose_name_plural': 'Paiements locataires',
                'ordering': ['-mois', '-date_paiement'],
                'indexes': [models.Index(fields=['mois', 'contrat'], name='paiements_p_mois_3d6aac_idx'), models.Index(fields=['date_paiement'], name='paiements_p_date_pa_fc885d_idx'), models.Index(fields=['statut'], name='paiements_p_statut_12a767_idx')],
            },
        ),
    ]
