# Generated by Django 5.2.9 on 2025-12-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiements', '0001_initial'),
        ('quittances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementlocataire',
            name='quittance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement_associe', to='quittances.quittance', verbose_name='Quittance générée'),
        ),
        migrations.AddIndex(
            model_name='paiementlocataire',
            index=models.Index(fields=['mois', 'contrat'], name='paiements_p_mois_3d6aac_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementlocataire',
            index=models.Index(fields=['date_paiement'], name='paiements_p_date_pa_fc885d_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementlocataire',
            index=models.Index(fields=['statut'], name='paiements_p_statut_12a767_idx'),
        ),
    ]
