# Generated by Django 5.2.6 on 2025-10-22 12:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immeuble', '0017_alter_appartement_created_at_and_more'),
        ('persons', '0014_alter_locataires_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 10, 22, 12, 27, 15, 572492))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_fin_effective', models.DateField(blank=True, null=True, verbose_name='Date de fin effective')),
                ('loyer_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Loyer mensuel hors charges')),
                ('charges_mensuelles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Charges mensuelles')),
                ('depot_garantie', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dépôt de garantie')),
                ('indice_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Indice de référence IRL')),
                ('date_revision', models.DateField(blank=True, null=True, verbose_name='Date de révision annuelle')),
                ('actif', models.BooleanField(default=True)),
                ('preavis_donne', models.BooleanField(default=False, verbose_name='Préavis donné')),
                ('date_preavis', models.DateField(blank=True, null=True)),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='contrats/', verbose_name='Fichier du contrat')),
                ('etat_lieux_entree', models.FileField(blank=True, null=True, upload_to='etats_lieux/', verbose_name="État des lieux d'entrée")),
                ('etat_lieux_sortie', models.FileField(blank=True, null=True, upload_to='etats_lieux/', verbose_name='État des lieux de sortie')),
                ('notes', models.TextField(blank=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='immeuble.appartement')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='persons.locataires')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_debut'],
            },
        ),
    ]
