# Generated by Django 5.2.9 on 2025-12-09 13:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immeuble', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratLocataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('principal', models.BooleanField(default=False, help_text='Locataire à contacter en priorité', verbose_name='Contact principal')),
                ('ordre', models.PositiveSmallIntegerField(default=1, help_text="Ordre d'apparition sur les documents (1, 2, 3...)", verbose_name="Ordre d'affichage")),
                ('date_entree', models.DateField(help_text='Date à laquelle ce locataire a rejoint le bail', verbose_name="Date d'entrée dans le bail")),
                ('date_sortie', models.DateField(blank=True, help_text='Laisser vide si toujours sur le bail', null=True, verbose_name='Date de sortie du bail')),
                ('role', models.CharField(choices=[('titulaire', 'Titulaire'), ('cotitulaire', 'Co-titulaire'), ('garant', 'Garant')], default='cotitulaire', max_length=50, verbose_name='Rôle')),
                ('notes', models.TextField(blank=True, help_text='Notes spécifiques à cette relation locataire-contrat', verbose_name='Notes')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.locataires', verbose_name='Locataire')),
            ],
            options={
                'verbose_name': 'Locataire du contrat',
                'verbose_name_plural': 'Locataires du contrat',
                'ordering': ['ordre', 'date_entree'],
            },
        ),
        migrations.CreateModel(
            name='Contrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_fin_effective', models.DateField(blank=True, null=True, verbose_name='Date de fin effective')),
                ('loyer_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Loyer mensuel hors charges')),
                ('charges_mensuelles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Charges mensuelles')),
                ('jour_echeance', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name="Jour d'échéance")),
                ('depot_garantie', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dépôt de garantie')),
                ('indice_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Indice de référence IRL')),
                ('date_revision', models.DateField(blank=True, null=True, verbose_name='Date de révision annuelle')),
                ('actif', models.BooleanField(default=True)),
                ('preavis_donne', models.BooleanField(default=False, verbose_name='Préavis donné')),
                ('date_preavis', models.DateField(blank=True, null=True)),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='contrats/', verbose_name='Fichier du contrat')),
                ('etat_lieux_entree', models.FileField(blank=True, null=True, upload_to='etats_lieux/', verbose_name="État des lieux d'entrée")),
                ('etat_lieux_sortie', models.FileField(blank=True, null=True, upload_to='etats_lieux/', verbose_name='État des lieux de sortie')),
                ('notes', models.TextField(blank=True)),
                ('appartement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='immeuble.appartement')),
                ('locataires', models.ManyToManyField(related_name='contrats', through='contrats.ContratLocataire', to='persons.locataires', verbose_name='Locataires du bail')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='contratlocataire',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrats.contrats', verbose_name='Contrat'),
        ),
        migrations.AddIndex(
            model_name='contratlocataire',
            index=models.Index(fields=['contrat', 'principal'], name='contrats_co_contrat_74ec05_idx'),
        ),
        migrations.AddIndex(
            model_name='contratlocataire',
            index=models.Index(fields=['locataire', 'date_sortie'], name='contrats_co_locatai_4712f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contratlocataire',
            unique_together={('contrat', 'locataire')},
        ),
    ]
