# Generated by Django 5.2.6 on 2025-10-25 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 14, 8, 16, 145945)),
        ),
    ]
