# Generated by Django 5.2.6 on 2025-10-27 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_alter_contrats_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 12, 3, 9, 263271)),
        ),
    ]
