# Generated by Django 5.2.6 on 2025-10-29 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0003_alter_contrats_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 16, 1, 48, 323452)),
        ),
    ]
