# Generated by Django 5.2.7 on 2025-10-30 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0004_alter_contrats_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 30, 10, 8, 14, 680157)),
        ),
    ]
