# Generated by Django 5.2.6 on 2025-10-14 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locataires',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 14, 10, 48, 33, 709891)),
        ),
        migrations.AddField(
            model_name='locataires',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proprietaires',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 14, 10, 48, 33, 709891)),
        ),
        migrations.AddField(
            model_name='proprietaires',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
