# Generated by Django 5.2.6 on 2025-10-22 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_alter_locataires_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataires',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 12, 19, 8, 832187)),
        ),
        migrations.AlterField(
            model_name='proprietaires',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 12, 19, 8, 832187)),
        ),
    ]
