# Generated by Django 5.2.6 on 2025-10-25 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_alter_locataires_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataires',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 14, 8, 16, 145945)),
        ),
        migrations.AlterField(
            model_name='proprietaires',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 14, 8, 16, 145945)),
        ),
    ]
