# Generated by Django 5.2.6 on 2025-10-27 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0015_alter_locataires_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataires',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 12, 3, 9, 263271)),
        ),
        migrations.AlterField(
            model_name='proprietaires',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 12, 3, 9, 263271)),
        ),
    ]
