# Generated by Django 5.2.7 on 2025-10-29 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0016_alter_locataires_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locataires',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 8, 55, 2, 568305)),
        ),
        migrations.AlterField(
            model_name='proprietaires',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 8, 55, 2, 568305)),
        ),
    ]
