# Generated by Django 5.2.9 on 2025-12-09 13:46

import django.db.models.deletion
import quittances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('mois', models.DateField(verbose_name='Mois concerné')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Numéro de quittance')),
                ('loyer', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Loyer hors charges')),
                ('charges', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Charges')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('fichier_pdf', models.FileField(blank=True, upload_to=quittances.models.quittance_upload_path, verbose_name='Fichier PDF')),
                ('envoyee', models.BooleanField(default=False, verbose_name='Envoyée')),
                ('mode_envoi', models.CharField(blank=True, choices=[('email', 'Email'), ('courrier', 'Courrier postal'), ('remise_main', 'Remise en main propre'), ('portail', 'Téléchargée sur portail')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittances', to='contrats.contrats')),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quittance_generee', to='paiements.paiementlocataire', verbose_name='Paiement associé')),
            ],
            options={
                'verbose_name': 'Quittance',
                'verbose_name_plural': 'Quittances',
                'ordering': ['-mois', '-date_generation'],
                'indexes': [models.Index(fields=['mois', 'contrat'], name='quittances__mois_33a323_idx'), models.Index(fields=['numero'], name='quittances__numero_ae74b4_idx'), models.Index(fields=['envoyee'], name='quittances__envoyee_9d4013_idx')],
                'unique_together': {('contrat', 'mois')},
            },
        ),
    ]
